mybatis-plus:
    configuration:
        cache-enabled: false
        jdbc-type-for-null: 'null'
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            logic-delete-value: 2
            logic-not-delete-value: 0
    mapper-locations: classpath:/mapper/*.xml
    #type-aliases-package: com.example.demo.domain
server:
    port: 8090
spring:
    autoconfigure:
        exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
    datasource:
        druid:
            connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            exception-sorter: true
            filters: stat,wall,log4j
            initial-size: 10
            max-active: 100
            max-pool-prepared-statement-per-connection-size: 20
            max-wait: 20000
            min-evictable-idle-time-millis: 30000
            min-idle: 10
            pool-prepared-statements: true
            stat-view-servlet:
                enabled: true
                login-password: 123456
                login-username: admin
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 20000
            use-global-data-source-stat: true
    profiles:
        active: dev
